### ISSUE TITLE
Update 'opn' to 'open'

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/program-wars#515]
The `opn` library is deprecated and should be changed to `open` (https://www.npmjs.com/package/opn). It should be as easy as adding an 'e' in a few places in `build/dev-server.js`.

However, this causes the `npm run dev` to fail:
```
/home/anvik/program-wars/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                               ^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/anvik/program-wars/build/dev-server.js:8:12)
```

**Comment by johnanvik** [comment]
Was able to at least move `opn` to v.5.5.0

**Comment by johnanvik** [comment]
Resovled in #550
